### ISSUE TITLE
Import des devices

### ISSUE THREAD

**Issue by mika-nt28** [mika-nt28/Jeedom-libreNMS#20]

**Comment by mika-nt28** [comment]
@poluket est ce que tu as validé cette import?

**Comment by poluket** [comment]
non, il n'est pas bon. j'ai supprimé et reinstallé le plugin pour partir de 0.

lorsque je clic sur "importer les equipements"
il n'y a rien qui se passe
![2018-09-27 10_56_17-librenms - jeedom](https://user-images.githubusercontent.com/43402274/46134801-0a3af200-c244-11e8-8474-fded0772d971.png)

et je n'ai pas de log.

**Comment by mika-nt28** [comment]
Je pense que c'est le même problème que pour les commandes.
Ils ont mis un etage qui ne sert a rien.

J'ai modifier le code d'import
Peux tu tester?

**Comment by poluket** [comment]
cela ne fonctionne pas, j'ai ajouté une ligne de log au debut de la fonction:
```
public static function getDevice() {
      	log::add('libreNMS','debug','test');
		$result=self::Request('/api/v0/devices');
```
et rien n'apparait dans les logs, donc pour moi la fonction n'est pas appelée ou i y a une erreur avant.

**Comment by mika-nt28** [comment]
Arf il y a une erreur de copie collé dans l'ajax.
J'ai corrigé

**Comment by poluket** [comment]
ok pour moi en supprimant le [0]

**Comment by poluket** [comment]
cosmetique, corrigé le message en vert au dessus "Suppression effectuée avec succès" par "Ajout effectué avec succès"
