### ISSUE TITLE
Intégration des commande Services

### ISSUE THREAD

**Issue by mika-nt28** [mika-nt28/Jeedom-libreNMS#24]
Intégrer dans la dernière version a tester

- Sélection dans la configuration de
- Création des commandes

**Comment by poluket** [comment]
cela fonctionne
![2018-09-26 14_19_22-dashboard - jeedom](https://user-images.githubusercontent.com/43402274/46079366-45cbb280-c197-11e8-8d4f-e75ef4e460f0.png)

**Comment by mika-nt28** [comment]
Par contre je me rende compte qu'il sont identique

**Comment by poluket** [comment]
oui, pour moi, system, c'est l'info de librenms et pas des devices monitorés

**Comment by mika-nt28** [comment]
Oui je l'ai supprimer des commande pour le mettre sur la page santé

**Comment by poluket** [comment]
super idée
