### ISSUE TITLE
proposition: création d'icones en fonction du type de device

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-libreNMS#36]
comme le titre le dit, avoir des icones en fonction des différents type de device existants

```
<option value="server">{{Serveur}}</option>
<option value="network">{{Réseau}}</option>
<option value="wireless">{{Réseau sans fil}}</option>
<option value="firewall">{{Pare feu}}</option>
<option value="power">{{Alimentation}}</option>
<option value="environment">{{Environnemet}}</option>
<option value="loadbalancer">{{Equilibreur de charge}}</option>
<option value="storage">{{Disque}}</option>
<option value="printer">{{Imprimante}}</option>
<option value="appliance">{{Appliance}}</option>
<option value="collaboration">{{Collaboration}}</option>
<option value="workstation">{{Station de travail}}</option>
```

**Comment by mika-nt28** [comment]
C'est possible est ce que tu te sens de les faire?

**Comment by mika-nt28** [comment]
J'ai modifier le code de la page pour afficher les icone spécifique si le fichier existe
a placé ici
$file='core/config/devices/'.$eqLogic->getConfiguration('type').'.png';

**Comment by mika-nt28** [comment]
J'ai fait le teste concluant avec le type server.
Il faut juste cree toutes les autres icone a mettre dans le dossier core/config/devices/

**Comment by poluket** [comment]
je vais regarder pour faire cela

**Comment by poluket** [comment]
je cherche a uploader les fichiers mais ce n'est pas autorisé. et dans mon folk, je n'ai pas le dossier ....

je suis un peu perdu, je vois pas comment placer les images

**Comment by mika-nt28** [comment]
A tu fait un merge de celui si car je les ai cree

**Comment by poluket** [comment]
trouvé
